name: Build Debian Packages

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

jobs:
  identify-version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.set_version.outputs.version }}
    steps:
    - name: Checkout code repository
      uses: actions/checkout@v6
    - name: Set app version
      id: set_version
      run: |
        .github/scripts/identify-version.sh
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: amd64
            runs-on: ubuntu-latest
            stage: rel
          - architecture: arm64
            runs-on: ubuntu-24.04-arm
            container: docker.cloudsmith.io/adi/containers/kuiper_basic_64:latest
            stage: rel
          - architecture: armhf
            runs-on: ubuntu-24.04-arm
            container: docker.cloudsmith.io/adi/containers/kuiper_basic_32:latest
            platform: linux/arm/v7
            stage: rel
          - architecture: amd64
            runs-on: ubuntu-latest
            stage: dev
            artifact-name: Linux-Ubuntu-24.04.deb
          - architecture: arm64
            runs-on: ubuntu-24.04-arm
            container: docker.cloudsmith.io/adi/containers/kuiper_basic_64:latest
            stage: dev
            artifact-name: Debian-13-arm64.deb
          - architecture: armhf
            runs-on: ubuntu-24.04-arm
            container: docker.cloudsmith.io/adi/containers/kuiper_basic_32:latest
            platform: linux/arm/v7
            stage: dev
            artifact-name: Debian-13-armhf.deb
    runs-on: ${{ matrix.runs-on }}
    needs: identify-version
    container: ${{ matrix.architecture == 'arm64' && matrix.container || '' }}
    env:
      ARCHITECTURE: ${{ matrix.architecture }}
      CONTAINER: ${{ matrix.container }}
      VERSION: ${{needs.identify-version.outputs.app-version}}
      ARTIFACT_NAME: ${{ matrix.artifact-name || '' }}
      CMAKE_OPTIONS: '-DPYTHON_BINDINGS=ON -DENABLE_PACKAGING=ON -DDEB_DETECT_DEPENDENCIES=ON'
      STAGE: ${{ matrix.stage }}
      LD_LIBRARY_PATH: /usr/local/lib
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install deps
        shell: sh
        run: |
          .github/scripts/install-deps.sh
      - name: Create debian package - amd64/arm64
        if: ${{ matrix.architecture == 'amd64' || matrix.architecture == 'arm64' }}
        id: build_deb
        uses: analogdevicesinc/shared-actions/deb-generator-action@main
        with:
          working-directory: .
          ignore-path: |
            packaging
          control-path: ${{ matrix.stage == 'dev' && 'packaging/debian_dev' || 'packaging/debian' }}
          version: ${{ env.VERSION }}
      - name: Install and verify application
        shell: sh
        run: |
          .github/scripts/install-app.sh
        env:
          ARTIFACTS_DIR: ${{ steps.build_deb.outputs.artifact-dir || '' }}
      - name: Upload debian artifacts to github
        uses: actions/upload-artifact@v7
        with:
          name: colorimeter-debian-${{ matrix.architecture }}-${{ matrix.stage }}
          path: |
            artifacts/
          if-no-files-found: error
